import { Product, Category, Review, Order } from './types';

export const categories: Category[] = [
  { id: 'electronics', name: 'Electronics', icon: '💻', count: 1240, gradient: 'from-blue-600 to-cyan-500' },
  { id: 'fashion', name: 'Fashion', icon: '👗', count: 3820, gradient: 'from-pink-600 to-rose-500' },
  { id: 'home', name: 'Home & Living', icon: '🏡', count: 2150, gradient: 'from-amber-600 to-orange-500' },
  { id: 'sports', name: 'Sports', icon: '⚽', count: 980, gradient: 'from-green-600 to-emerald-500' },
  { id: 'beauty', name: 'Beauty', icon: '💄', count: 1670, gradient: 'from-purple-600 to-violet-500' },
  { id: 'books', name: 'Books', icon: '📚', count: 4500, gradient: 'from-indigo-600 to-blue-500' },
  { id: 'toys', name: 'Toys & Games', icon: '🎮', count: 760, gradient: 'from-red-600 to-orange-500' },
  { id: 'food', name: 'Food & Drinks', icon: '🍕', count: 1320, gradient: 'from-yellow-600 to-amber-500' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'ProMax Wireless Headphones X1',
    description: 'Experience crystal-clear audio with our flagship wireless headphones. Featuring active noise cancellation, 40-hour battery life, and premium leather ear cushions.',
    price: 299.99,
    originalPrice: 449.99,
    rating: 4.8,
    reviewCount: 2847,
    category: 'electronics',
    tags: ['wireless', 'noise-cancelling', 'premium'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      'https://images.unsplash.com/photo-1545127398-14699f92334b?w=600&q=80',
    ],
    inStock: true,
    badge: 'sale',
    seller: { name: 'AudioTech Pro', avatar: 'AT', rating: 4.9 },
  },
  {
    id: '2',
    name: 'Ultra Slim Laptop Stand Pro',
    description: 'Elevate your workspace with this premium aluminum laptop stand. Adjustable angles, heat dissipation, and foldable design for portability.',
    price: 89.99,
    originalPrice: 120.00,
    rating: 4.6,
    reviewCount: 1253,
    category: 'electronics',
    tags: ['ergonomic', 'aluminum', 'portable'],
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80'],
    inStock: true,
    badge: 'hot',
    seller: { name: 'DeskMate', avatar: 'DM', rating: 4.7 },
  },
  {
    id: '3',
    name: 'Luxury Leather Crossbody Bag',
    description: 'Handcrafted genuine leather crossbody bag with gold hardware. Spacious interior with multiple compartments for everyday essentials.',
    price: 189.00,
    rating: 4.9,
    reviewCount: 892,
    category: 'fashion',
    tags: ['leather', 'handcrafted', 'luxury'],
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80'],
    inStock: true,
    badge: 'new',
    seller: { name: 'LuxeLeather', avatar: 'LL', rating: 4.9 },
  },
  {
    id: '4',
    name: 'Smart Home Hub Station',
    description: 'Control all your smart devices from one hub. Compatible with Alexa, Google Home, and Apple HomeKit. Touchscreen display with voice commands.',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviewCount: 3420,
    category: 'electronics',
    tags: ['smart-home', 'voice-control', 'hub'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    inStock: true,
    badge: 'sale',
    seller: { name: 'SmartLife', avatar: 'SL', rating: 4.6 },
  },
  {
    id: '5',
    name: 'Premium Yoga Mat Pro',
    description: 'Professional-grade yoga mat with alignment lines, non-slip surface, and extra thick cushioning. Eco-friendly materials, free carrying strap.',
    price: 78.00,
    rating: 4.7,
    reviewCount: 5621,
    category: 'sports',
    tags: ['yoga', 'eco-friendly', 'non-slip'],
    image: 'https://images.unsplash.com/photo-1601925228429-1d4bc5db5e4e?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1601925228429-1d4bc5db5e4e?w=600&q=80'],
    inStock: true,
    badge: 'hot',
    seller: { name: 'ZenFit', avatar: 'ZF', rating: 4.8 },
  },
  {
    id: '6',
    name: 'Artisan Coffee Blend Set',
    description: 'Curated collection of 6 single-origin coffee beans from around the world. Each 250g bag is freshly roasted and vacuum-sealed.',
    price: 64.99,
    rating: 4.9,
    reviewCount: 2187,
    category: 'food',
    tags: ['coffee', 'artisan', 'single-origin'],
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80'],
    inStock: true,
    badge: 'new',
    seller: { name: 'BeanMaster', avatar: 'BM', rating: 4.9 },
  },
  {
    id: '7',
    name: 'Minimalist Mechanical Keyboard',
    description: 'Compact 75% layout mechanical keyboard with hot-swappable switches, RGB backlighting, and aircraft-grade aluminum casing.',
    price: 199.00,
    originalPrice: 249.00,
    rating: 4.7,
    reviewCount: 1893,
    category: 'electronics',
    tags: ['mechanical', 'rgb', 'compact'],
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80'],
    inStock: true,
    badge: 'sale',
    seller: { name: 'KeyCraft', avatar: 'KC', rating: 4.7 },
  },
  {
    id: '8',
    name: 'Scented Soy Candle Collection',
    description: 'Set of 3 hand-poured soy candles with essential oil scents: Lavender & Sage, Cedar & Vanilla, and Ocean Breeze. 50+ hour burn time each.',
    price: 45.00,
    rating: 4.8,
    reviewCount: 4312,
    category: 'home',
    tags: ['candles', 'soy', 'handmade'],
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80'],
    inStock: true,
    badge: 'limited',
    seller: { name: 'WickWorks', avatar: 'WW', rating: 4.8 },
  },
  {
    id: '9',
    name: 'Vitamin C Serum Luxury Kit',
    description: 'Complete skincare routine with 20% Vitamin C serum, hyaluronic acid moisturizer, and SPF 50 sunscreen. Dermatologist tested.',
    price: 125.00,
    originalPrice: 180.00,
    rating: 4.6,
    reviewCount: 6743,
    category: 'beauty',
    tags: ['skincare', 'vitamin-c', 'anti-aging'],
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80'],
    inStock: true,
    badge: 'hot',
    seller: { name: 'GlowLab', avatar: 'GL', rating: 4.7 },
  },
  {
    id: '10',
    name: 'Wireless Charging Desk Pad',
    description: 'Extra-large desk mat with built-in 15W wireless charging. Anti-slip base, waterproof surface, and integrated cable management.',
    price: 69.99,
    rating: 4.5,
    reviewCount: 987,
    category: 'electronics',
    tags: ['wireless-charging', 'desk', 'waterproof'],
    image: 'https://images.unsplash.com/photo-1616628188506-4d8b3404fadd?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1616628188506-4d8b3404fadd?w=600&q=80'],
    inStock: false,
    badge: 'new',
    seller: { name: 'DeskTech', avatar: 'DT', rating: 4.5 },
  },
  {
    id: '11',
    name: 'Premium Running Shoes X7',
    description: 'Carbon fiber plate running shoes with advanced foam technology. Lightweight 210g, wide toe box, and reflective safety strips.',
    price: 219.99,
    originalPrice: 279.99,
    rating: 4.8,
    reviewCount: 3214,
    category: 'sports',
    tags: ['running', 'carbon-fiber', 'lightweight'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'],
    inStock: true,
    badge: 'sale',
    seller: { name: 'RunElite', avatar: 'RE', rating: 4.8 },
  },
  {
    id: '12',
    name: 'Illustrated Fantasy Novel Set',
    description: 'Limited edition boxed set of the award-winning fantasy trilogy with exclusive illustrations, gold foil covers, and author signatures.',
    price: 89.99,
    rating: 4.9,
    reviewCount: 1567,
    category: 'books',
    tags: ['fantasy', 'illustrated', 'limited-edition'],
    image: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80'],
    inStock: true,
    badge: 'limited',
    seller: { name: 'Bookcraft', avatar: 'BC', rating: 4.9 },
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    user: 'Sarah M.',
    avatar: 'SM',
    rating: 5,
    date: '2 days ago',
    comment: 'Absolutely love this product! The quality exceeds expectations. Fast shipping and beautiful packaging.',
    helpful: 42,
  },
  {
    id: 'r2',
    user: 'James K.',
    avatar: 'JK',
    rating: 4,
    date: '1 week ago',
    comment: 'Great product overall. Build quality is excellent. Only minor issue was the setup time but worth it.',
    helpful: 28,
  },
  {
    id: 'r3',
    user: 'Emily R.',
    avatar: 'ER',
    rating: 5,
    date: '2 weeks ago',
    comment: 'This is the best purchase I\'ve made this year! Highly recommend to everyone looking for premium quality.',
    helpful: 67,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    date: '2026-06-18',
    status: 'delivered',
    total: 389.98,
    items: [
      { product: products[0], quantity: 1 },
      { product: products[4], quantity: 1 },
    ],
  },
  {
    id: 'ORD-002',
    date: '2026-06-15',
    status: 'shipped',
    total: 189.00,
    items: [{ product: products[2], quantity: 1 }],
  },
  {
    id: 'ORD-003',
    date: '2026-06-10',
    status: 'processing',
    total: 269.97,
    items: [
      { product: products[7], quantity: 2 },
      { product: products[5], quantity: 1 },
    ],
  },
];
